[build]
    publish = "client/dist"

[[redirects]]
    from = "*"
    to = "https://stock-wise-1.onrender.com/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
