[build]
    publish = "client/dist"
[[redirects]]
  from = "/api/*"
  to = "https://stock-wise-1.onrender.com/api/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
